<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net9.0;net10.0</TargetFrameworks>
		<LangVersion>9.0</LangVersion>
		<Version>0.0.1</Version>
		<Nullable>enable</Nullable>
		<AssemblyName>MajProtocol</AssemblyName>
		<RootNamespace>MajProtocol</RootNamespace>

		<Title>MajProtocol</Title>
		<Description>Majdata protocol types.</Description>

		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="LICENSE" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
</Project>
