<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<LangVersion>9.0</LangVersion>
		<Version>0.0.1</Version>
		<Nullable>enable</Nullable>
		<AssemblyName>MajWebSocket</AssemblyName>
		<RootNamespace>MajWebSocket</RootNamespace>
		<Title>MajWebSocket</Title>
		<Description>Majdata WebSocket wire-protocol types.</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
</Project>
